package com.example.lab23a.model;

import java.time.LocalDate;

public class UserLearnStyle {
	
	private boolean isShuffleOn;
	private boolean autoSaveOn;
	private int lastUsedIndex;
	private int lastUsedIndexFolder;
	private LocalDate lastStudiedDate;
	private int userStreakInDays;

	private String lastSavedFileAbsolutePath = "C:\\";

	/**
	 * Creates learn style with default settings
	 */
	public UserLearnStyle() {
		defaultSettings();
	}

	/**
	 * Applies default settings.
	 * More specified: shuffle terms in write mode, automatically save progress.
	 */
	public void defaultSettings() {
		isShuffleOn = true;
		autoSaveOn = true;
	}

	/**
	 *
	 * @return date, when user studied last time
	 */
	public LocalDate getLastStudied() {
		return lastStudiedDate;
	}

	/**
	 *
	 * @param date - date, when user studied last time
	 */
	public void setLastStudied(LocalDate date) {
		lastStudiedDate = date;
	}

	/**
	 *
	 * @param isShuffleOn - option that determines, whether the terms are shuffled in write mode
	 */
	public void setShuffleOn(boolean isShuffleOn) {
		this.isShuffleOn = isShuffleOn;
	}

	/**
	 *
	 * @param value - option that determines, whether the user data automatically saves on the background
	 */
	public void setAutoSaveOn(boolean value) {
		this.autoSaveOn = value;
	}

	/**
	 *
	 * @return true, if terms will be shuffled in write mode
	 */
	public boolean getIsShuffleOn() {
		return this.isShuffleOn;
	}

	/**
	 *
	 * @return true, if data is saving automatically on the background
	 */
	public boolean getAutosaveOn() {
		return this.autoSaveOn;
	}

	/**
	 *
	 * @return index of last created study set (even if it was deleted)
	 */
	public int getLastUsedIndex() {
		return lastUsedIndex;
	}

	/**
	 *
	 * @param lastUsedIndex - updates index of last created study set. Can't be less than previous value.
	 */
	public void setLastUsedIndex(int lastUsedIndex) {
		this.lastUsedIndex = Math.max(this.lastUsedIndex, lastUsedIndex);
	}

	/**
	 *
	 * @return index of last created folder (even if it was deleted)
	 */
	public int getLastUsedIndexFolder() {
		return lastUsedIndexFolder;
	}

	/**
	 *
	 * @param lastUsedIndexFolder - updates index of last created folder. Can't be less than previous value.
	 */
	public void setLastUsedIndexFolder(int lastUsedIndexFolder) {
		this.lastUsedIndexFolder = Math.max(lastUsedIndexFolder, this.lastUsedIndex);
	}

	/**
	 * Sets last studied dae to current date
	 */
	private void updateLastStudiedDate() {
		this.lastStudiedDate = Dates.currentDate().toLocalDate();
	}
	/**
	 * Sets streak to 0 if user skipped a day of studying 
	 */
	public void initStreak() {
		if (lastStudiedDate == null) {
			lastStudiedDate = Dates.currentDate().toLocalDate();
			this.userStreakInDays = 0;
		}
		else if (Dates.compareDaysPassed(Dates.currentDate().toLocalDate(), lastStudiedDate) > 1) {
			this.userStreakInDays = 0;
		}
	}
	/**
	 * Increments user's streak if it hasn't been done today
	 */
	public void updateStreak() {
		if (Dates.compareDaysPassed(Dates.currentDate().toLocalDate(), lastStudiedDate) == 1 || userStreakInDays == 0) {
			updateLastStudiedDate();
			userStreakInDays++;
		}
	}
	/**
	 * 
	 * @return number of days that user has studied in a row
	 */
	public int getStreak() {
		return userStreakInDays;
	}
	public void setStreak(int days) {
		this.userStreakInDays = days;
	}
	/**
	 * 
	 * @return empty string if user doesn't have a streak or a message that states how many days in a row user have
	 */
	public String getStreakText() {
		if (userStreakInDays == 0)
			return "";
		else 
			return "You are on a " + userStreakInDays + "-day streak!";
	}

	/**
	 *
	 * @return the absolute file path, which was chosen to save PDF document, generated by this app.
	 */
	public String getLastSavedFileAbsolutePath() {
		return lastSavedFileAbsolutePath;
	}

	/**
	 *
	 * @param newPath - path, which was chosen to save PDF document, so that it can be used next time.
	 */
	public void updateLastSavedFileAbsolutePath(String newPath) {
		this.lastSavedFileAbsolutePath = newPath;
	}
}
