package com.example.lab23a.model;

public class UserSavedInfo {
    private int lastUsedIndex;
    private int lastUsedIndexFolder;


    private String lastSavedFileAbsolutePath = "C:\\";


    /**
     *
     * @return index of last created study set (even if it was deleted)
     */
    public int getLastUsedIndex() {
        return lastUsedIndex;
    }

    /**
     *
     * @param lastUsedIndex - updates index of last created study set. Can't be less than previous value.
     */
    public void setLastUsedIndex(int lastUsedIndex) {
        this.lastUsedIndex = Math.max(this.lastUsedIndex, lastUsedIndex);
    }

    /**
     *
     * @return index of last created folder (even if it was deleted)
     */
    public int getLastUsedIndexFolder() {
        return lastUsedIndexFolder;
    }

    /**
     *
     * @param lastUsedIndexFolder - updates index of last created folder. Can't be less than previous value.
     */
    public void setLastUsedIndexFolder(int lastUsedIndexFolder) {
        this.lastUsedIndexFolder = Math.max(lastUsedIndexFolder, this.lastUsedIndex);
    }



    /**
     *
     * @return the absolute file path, which was chosen to save PDF document, generated by this app.
     */
    public String getLastSavedFileAbsolutePath() {
        return lastSavedFileAbsolutePath;
    }

    /**
     *
     * @param newPath - path, which was chosen to save PDF document, so that it can be used next time.
     */
    public void updateLastSavedFileAbsolutePath(String newPath) {
        this.lastSavedFileAbsolutePath = newPath;
    }
}
